name: tanecavu
favicon: null
layout_spectrum: 0
typography_spectrum: 0.48106
title: tanecavu
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0c0c'
    - '#999999'
    - '#c8c8c8'
    - '#404040'
    - '#6f6f6f'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
