name: tanecavu
favicon: null
layout_spectrum: 0.125016285572201
typography_spectrum: 0.5135630324948579
title: tanecavu
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121214'
    - '#373739'
    - '#a0a0a2'
    - '#f4f4f6'
    - '#737375'
  brandStrength: 0.13043784629553556
  lightness: 0.529488860629499
  saturation: 0.22404584102332592
  rhythmicContrast: 0.11827077041380107
purpose: []
