name: tanecavu
favicon: null
layout_spectrum: 0
typography_spectrum: 0.48106
title: tanecavu
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73263115-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#cfcfcf'
    - '#757575'
    - '#878787'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
