name: tanecavu
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5135630324948579
title: tanecavu
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#0e0e10'
    - '#d1d1d1'
    - '#6a6a6c'
    - '#3f3f41'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.11827077041380107
purpose: []
